#!/usr/bin/env ruby
# frozen_string_literal: true

require "pdf_links_checker"
require "pdf_links_checker/pdf_document"

file_name = ARGV[0]
file_path = "#{Dir.pwd}/#{file_name}"
links =  PdfLinksChecker::PdfDocument.from(file_path).links
puts "Working links: #{links.valid_count} of #{links.total_count}"
links.invalid.each { |invalid_link| puts invalid_link }
